#ifndef RINGBUFFER_VISIBILITY_H
#define RINGBUFFER_VISIBILITY_H

#include "ringbuffer/config.h"

#ifndef RINGBUFFER_BUILD_STATIC
#if defined(RINGBUFFER_EXPORTS)
#define RINGBUFFER_EXPORT RINGBUFFER_VISIBILITY_EXPORT
#else
#define RINGBUFFER_EXPORT RINGBUFFER_VISIBILITY_IMPORT
#endif
#else
#define RINGBUFFER_EXPORT RINGBUFFER_VISIBILITY_STATIC
#endif
#define RINGBUFFER_LOCAL RINGBUFFER_VISIBILITY_LOCAL

#endif //RINGBUFFER_VISIBILITY_H